### ISSUE TITLE
Scripts for creating Substrate FrontEnd templates

### ISSUE THREAD

**Issue by wirednkod** [polkadot-cloud/library#173]
It will be a great idea (thnx @shawntabrizi ) to have an `npx` or `npm create` script that the user would be able to setup fastly a react app (maybe even include `polkadotjs-api`, or `polkadot-api` or `light client/substrate-connect` setup) and polkadot-cloud, for a user to start working on his dApp idea.

Something similar to `npm create vite@latest` - e.g. `npm create polkadot-cloud-template`:

![image](https://github.com/polkadot-cloud/library/assets/5408605/2e87173b-0031-4678-851a-d478ed7ec9b9)

**Comment by wirednkod** [comment]
An example:
```
~ npm create polkadot-cloud-app@latest

- Which API you want to use?
[ ] PolkadotJs API
[ ] Polkadot API

- Chose your @polkadot-cloud theme?
[ ] Polkadot
[ ] Kusama
[ ] Other (custom)

- Choose menu Layout
[ ] Left
[ ] Right
[ ] Top

- Is menu collapsable?
[ ] Yes
[ ] No
```

**Comment by shawntabrizi** [comment]
> - Which API you want to use?
> [ ] PolkadotJs API
> [ ] Polkadot API

I think clearly this will need some refinement. Better to just link to github rather than use a name

**Comment by wirednkod** [comment]
Closing here. Will address in https://github.com/polkadot-ui/library/issues/6
